services:
  movieapi:
    build: .
    container_name: movieapi
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=movie_db;Username=postgres;Password=postgres

  postgres:
    image: postgres:16-alpine
    container_name: movieapi_postgres
    restart: always
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
